Editorial Pass through IaC Docs
sassoftware/viya4-iac-azure pull request #176
Opened 2021-07-13 14:02 UTC by supear

Edited the docs. Attempted to bridge the gap between IaC docs and SAS official user deployment docs.

2021-07-15 13:06 UTC, RichWellum approved these changes
It LGTM with one small typo.

Note that in .md files you do not need to represent code with:

```bash
command
```
You can just indent the command:
    command

This does save a lot of space if you a documenting a lot of commands.

2021-07-26 12:57 UTC, thpang commented on README.md
> +  >- Azure Container Registry (optional)
So here, the wording and capitalization is being used to identify items relevant to the provider. Is there a reason the casing was adjusted? It should be reverted.

This needs to be removed: _Azure Premium Managed Disks (standard deployments);_ 

_NFS Server_ should be NFS Server (standard)
_Azure NetApp Files (HA deployments)_ should just have (HA) 

These values are part of the code base and identify with a given storage type.

2021-07-26 12:59 UTC, thpang commented on README.md
> +This project helps you to automate the cluster-provisioning phase of SAS Viya deployment. To learn about all phases and options of the
We've been told to use SAS Viya 4 in our docs for these projects and now the '4' is being removed. Have we, SAS, changed directions on this? If we have a version '5' and the code base is still relevant we can adjust. Just asking as this was a key sticking point when the repos were created. Hence their names `viay4-iac-xxxxxxx`

2021-07-26 13:03 UTC, thpang commented on README.md
> +Deployment Operator to deploy SAS Viya in your cloud environment. For more information about SAS Viya requirements and documentation for the deployment
You can't just use the SAS Deployment Operator, unless you manually perform all of the tasks that are covered in the `viya4-deployement` repo during the `baseline,install` step.

Change this line:

Once the cloud resources are provisioned, you can use the tools in 

Once the cloud resources are provisioned, use the 

There no separate tools in the viya4-deployment repo

2021-07-26 13:09 UTC, thpang commented on README.md
> +Terraform scripts require variable definitions as input. Many variables do not have default values. Create a file named
The statement Many variables do not have default values is a bit misleading. If the user chooses to use the `default` sample file which has very few lines, a cluster will be created. Most exposed variables have defaults which allows very minimal effort by the end user when creating a cluster.  Either remove the sentence or reword. Not sure what would go in its place.

2021-07-26 13:12 UTC, thpang commented on README.md
> +Create and manage the required cloud resources. Take one of the following steps:
Take one of the following steps -> Choose one of the following steps.

As a note we do have a preference to steer the client toward using Docker. Not sure if that's mentioned here, but it should be the default when referencing items.

2021-07-26 13:13 UTC, thpang commented on README.md
> +- run the [Docker container](docs/user/DockerUsage.md)
Again, need to emphasize Docker is the prefered method.

2021-07-26 13:23 UTC, thpang commented on docs/CONFIG-VARS.md
> +| nfs_raid_disk_type | Managed disk types | string | "Standard_LRS" | Supported values are as follows: Standard_LRS, Premium_LRS, StandardSSD_LRS or UltraSSD_LRS. When using `UltraSSD_LRS`, `nfs_vm_z
This is a list of parameters. 'as follows' seems out of place here. It is a definitive list of items to use.

2021-07-26 13:33 UTC, thpang commented on examples/sample-input-byo.tfvars
> +# Jump Server
We actually call it the 'Jump Box' here and in most docs. This will need to stay as 'Jump Box'

2021-07-26 13:33 UTC, thpang commented on examples/sample-input-ha.tfvars
> +# Jump Server
Same as above stays as 'Jump Box'

2021-07-26 13:34 UTC, thpang commented on examples/sample-input-minimal.tfvars
> +# Jump Server
Same as above stays as 'Jump Box'

2021-07-26 13:34 UTC, thpang commented on examples/sample-input-ppg.tfvars
> +# Jump Server
Same as above stays as 'Jump Box'

2021-07-26 13:34 UTC, thpang commented on examples/sample-input.tfvars
> +# Jump Server
Same as above stays as 'Jump Box'

2021-07-26 13:35 UTC, thpang requested changes
@supear Thanks again for going through our docs/examples/etc. Comments/Changes are ready for your review.

2021-07-26 16:45 UTC, thpang commented on README.md
> +This project contains Terraform scripts to provision the Microsoft Azure Cloud infrastructure resources that are required to deploy SAS Viya product offerings. Here is a list of resources that this p
Are the references to SAS Viya going to be reverted to SAS Viya 4 in the doc? If not and the company is moving to the more generic SAS Viya I am fine with that.

2021-07-27 12:50 UTC, thpang commented
@supear if you can roll-back the `SAS Viya` items to `SAS Viya 4` this pr should be good. I'll wait to hear from you.

2021-07-27 14:24 UTC, thpang commented on README.md
> -Once the cloud resources are provisioned, see the [viya4-deployment](https://github.com/sassoftware/viya4-deployment) repo to deploy SAS Viya 4 products. If you need more information on the SAS Viya
@supear these references need to be add back in as well.

2021-07-27 15:19 UTC, thpang approved these changes
Ok, so not all references to new entries that say `SAS Viya` have been converted to `SAS Viya 4` but will approve and fix shortly.

2021-08-06 13:41 UTC, merged